stages:
  - build
  - test

variables:
  FEATURES: ""

.stable:
  image: rust:latest
  cache:
    key: stable
    paths:
      - target/

.nightly:
  image: rustlang/rust:nightly
  cache:
    key: nightly
    paths:
      - target/

.build:
  stage: build
  script:
    - cargo build --verbose --no-default-features --features=$FEATURES

.test:
  stage: test
  script:
    - cargo test --verbose --no-default-features --features=$FEATURES

rust-latest-build:
  extends:
    - .build
    - .stable

rust-nightly-build:
  extends:
    - .build
    - .nightly


rust-latest-test:
  extends:
    - .test
    - .stable

rust-nightly-test:
  extends:
    - .test
    - .nightly
