[package]
name = "jid"
version = "0.3.1"
authors = ["lumi <lumi@pew.im>", "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>"]
description = "A crate which provides a Jid struct for Jabber IDs."
homepage = "https://gitlab.com/lumi/jid-rs"
repository = "https://gitlab.com/lumi/jid-rs"
documentation = "https://docs.rs/jid"
readme = "README.md"
keywords = ["xmpp", "jid"]
license = "LGPL-3.0+"

[badges]
gitlab = { repository = "lumi/jid-rs" }

[dependencies]
minidom = { version = "0.6.1", optional = true }
