[package]
name = "xmpp-parsers"
version = "0.1.0"
authors = ["Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>"]

[dependencies]
minidom = "0.1.1"
jid = "0.1.0"
base64 = "0.4.1"
sha2 = "0.5.0"
sha3 = "0.5.0"
blake2 = "0.5.0"
