[package]
name = "xmpp-parsers"
version = "0.11.1"
authors = [
  "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>",
  "Maxime “pep” Buquet <pep+code@bouah.net>",
]
description = "Collection of parsers and serialisers for XMPP extensions"
homepage = "https://hg.linkmauve.fr/xmpp-parsers"
repository = "https://hg.linkmauve.fr/xmpp-parsers"
keywords = ["xmpp", "xml"]
categories = ["parsing", "network-programming"]
license = "MPL-2.0"

[dependencies]
minidom = "0.9.1"
jid = { version = "0.5.2", features = ["minidom"] }
base64 = "0.9.2"
digest = "0.7.5"
sha-1 = "0.7.0"
sha2 = "0.7.1"
sha3 = "0.7.3"
blake2 = "0.7.1"
chrono = "0.4.5"
try_from = "0.2.2"

[features]
# Build xmpp-parsers to make components instead of clients.
component = []
