[package]
name = "xmpp"
version = "0.2.0"
authors = ["lumi <lumi@pew.im>", "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>"]
description = "A type-safe rust XMPP library. Still under development."
homepage = "https://gitlab.com/lumi/xmpp-rs"
repository = "https://gitlab.com/lumi/xmpp-rs"
documentation = "https://docs.rs/xmpp"
readme = "README.md"
keywords = ["xmpp", "xml"]
categories = ["network-programming"]
license = "LGPL-3.0+"

[badges]
gitlab = { repository = "lumi/xmpp-rs" }

[dependencies]
quick-xml = "0.10.0"
xmpp-parsers = "0.9.0"
openssl = "0.9.12"
base64 = "0.6.0"
minidom = "0.7.0"
jid = { version = "0.4", features = ["minidom"] }
sasl = "0.4.0"
sha-1 = "0.4"
chrono = "0.4.0"
try_from = "0.2.2"

[features]
insecure = []
