[package]
name = "minidom"
version = "0.6.0"
authors = ["lumi <lumi@pew.im>", "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>", "Bastien Orivel <eijebong+minidom@bananium.fr>", "Astro <astro@spaceboyz.net>"]
description = "A small, simple DOM implementation on top of quick-xml"
homepage = "https://gitlab.com/lumi/minidom-rs"
repository = "https://gitlab.com/lumi/minidom-rs"
documentation = "https://docs.rs/minidom"
readme = "README.md"
keywords = ["xml"]
license = "MIT"

[badges]
gitlab = { repository = "lumi/minidom-rs" }

[dependencies]
quick-xml = "0.7.3"
error-chain = "0.10.0"
