[package]
name = "xmpp"
version = "0.1.0"
authors = ["lumi <lumi@pew.im>"]

[dependencies]
xml-rs = "*"
openssl = "*"
base64 = "*"

[dependencies.minidom]
git = "https://gitlab.com/lumi/minidom-rs.git"
