[package]
name = "tokio-xmpp"
version = "1.0.0"
authors = ["Astro <astro@spaceboyz.net>", "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>", "pep <pep+code@bouah.net>", "O01eg <o01eg@yandex.ru>"]
description = "Asynchronous XMPP for Rust with tokio"
license = "MPL-2.0"
homepage = "https://gitlab.com/xmpp-rs/tokio-xmpp"
repository = "https://gitlab.com/xmpp-rs/tokio-xmpp"
documentation = "https://docs.rs/tokio-xmpp"
categories = ["asynchronous", "network-programming"]
keywords = ["xmpp", "tokio"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
bytes = "0.4"
xml5ever = "0.14"
native-tls = "0.2"
tokio-tls = "0.2"
sasl = "0.4"
trust-dns-resolver = "0.11"
trust-dns-proto = "0.7"
xmpp-parsers = "0.13"
idna = "0.1"
quick-xml = "0.13"
