[package]
name = "tokio-xmpp"
version = "0.2.2"
authors = ["Astro <astro@spaceboyz.net>", "Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>", "pep <pep+code@bouah.net>", "O01eg <o01eg@yandex.ru>"]
description = "Asynchronous XMPP for Rust with tokio"
license = "MPL-2.0"
homepage = "https://gitlab.com/xmpp-rs/tokio-xmpp"
repository = "https://gitlab.com/xmpp-rs/tokio-xmpp"
documentation = "https://docs.rs/tokio-xmpp"
categories = ["asynchronous", "network-programming"]
keywords = ["xmpp", "tokio"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
bytes = "0.4"
xml5ever = "0.12"
minidom = "0.9"
native-tls = "0.2"
tokio-tls = "0.2"
sasl = "0.4"
jid = { version = "0.5", features = ["minidom"] }
trust-dns-resolver = "0.9.1"
trust-dns-proto = "0.4.0"
xmpp-parsers = "0.11"
idna = "0.1"
try_from = "0.2"
quick-xml = "0.12"
derive-error = "0.0.4"
