[package]
name = "xmpp"
version = "0.2.0"
authors = ["lumi <lumi@pew.im>"]
description = "A type-safe rust XMPP library. Still under development."
homepage = "https://gitlab.com/lumi/xmpp-rs"
repository = "https://gitlab.com/lumi/xmpp-rs"
documentation = "https://docs.rs/xmpp"
readme = "README.md"
keywords = ["xmpp", "xml"]
categories = ["network-programming"]
license = "LGPL-3.0+"

[badges]
gitlab = { repository = "lumi/xmpp-rs" }

[dependencies]
xml-rs = "0.4.1"
openssl = "0.9.7"
base64 = "0.5.2"
minidom = "0.3.0"
jid = "0.2.0"
sasl = "0.3.0"
sha-1 = "0.3.2"

[features]
insecure = []
