[package]
name = "xmpp-parsers"
version = "0.4.0"
authors = ["Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>"]
description = "Collection of parsers and serialisers for XMPP extensions"
homepage = "https://hg.linkmauve.fr/xmpp-parsers"
repository = "https://hg.linkmauve.fr/xmpp-parsers"
keywords = ["xmpp", "xml"]
categories = ["parsing", "network-programming"]
license = "MPL-2.0"

[dependencies]
minidom = "0.4.3"
jid = "0.2.0"
base64 = "0.5.0"
digest = "0.5.0"
sha-1 = "0.3.0"
sha2 = "0.5.0"
sha3 = "0.5.0"
blake2 = "0.5.0"
chrono = "0.3.1"
