[workspace]
members = [  # alphabetically sorted
  "jid",
  "minidom",
  "tokio-xmpp",
  "xmpp-parsers",
  "xmpp",
]

[patch.crates-io]
jid = { path = "jid" }
minidom = { path = "minidom" }
tokio-xmpp = { path = "tokio-xmpp" }
xmpp-parsers = { path = "xmpp-parsers" }
xmpp = { path = "xmpp" }
